Section 1: Data Understanding & Preprocessing

In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

reading csv file

In [40]:
file=pd.read_csv("QS_World_University_Rankings_2025_Top_global_universities (1).csv",encoding='latin1')

Display first 5 rows

In [41]:
file.head()

,RANK_2025,RANK_2024,Institution_Name,Location,Region,SIZE,FOCUS,RES.,STATUS,Academic_Reputation_Score,...,International_Faculty_Rank,International_Students_Score,International_Students_Rank,International_Research_Network_Score,International_Research_Network_Rank,Employment_Outcomes_Score,Employment_Outcomes_Rank,Sustainability_Score,Sustainability_Rank,Overall_Score
0,1,1,Massachusetts Institute of Technology (MIT),United States,Americas,M,CO,VH,B,100.0,...,100,86.8,143,96.0,58,100.0,8,99.0,15=,100
1,2,6,Imperial College London,United Kingdom,Europe,L,FC,VH,A,98.5,...,66,99.6,44,97.4,34,93.4,61,99.7,6,98.5
2,3,3,University of Oxford,United Kingdom,Europe,L,FC,VH,A,100.0,...,120,97.7,73,100.0,1,100.0,3,85.0,126,96.9
3,4,4,Harvard University,United States,Americas,L,FC,VH,B,100.0,...,269,69.0,215,99.6,5,100.0,1,84.4,130,96.8
4,5,2,University of Cambridge,United Kingdom,Europe,L,FC,VH,A,100.0,...,73,94.8,98,99.3,10,100.0,5,84.8,127=,96.7

shape of dataset

In [42]:
file.shape

(1503, 28)

In [43]:
col=file.columns
data_type=file.dtypes
col,data_type

(Index(['RANK_2025', 'RANK_2024', 'Institution_Name', 'Location', 'Region',
        'SIZE', 'FOCUS', 'RES.', 'STATUS', 'Academic_Reputation_Score',
        'Academic_Reputation_Rank', 'Employer_Reputation_Score',
        'Employer_Reputation_Rank', 'Faculty_Student_Score',
        'Faculty_Student_Rank', 'Citations_per_Faculty_Score',
        'Citations_per_Faculty_Rank', 'International_Faculty_Score',
        'International_Faculty_Rank', 'International_Students_Score',
        'International_Students_Rank', 'International_Research_Network_Score',
        'International_Research_Network_Rank', 'Employment_Outcomes_Score',
        'Employment_Outcomes_Rank', 'Sustainability_Score',
        'Sustainability_Rank', 'Overall_Score'],
       dtype='str'),
 RANK_2025                                   str
 RANK_2024                                   str
 Institution_Name                            str
 Location                                    str
 Region                                      str
 SIZE                                        str
 FOCUS                                       str
 RES.                                        str
 STATUS                                      str
 Academic_Reputation_Score               float64
 Academic_Reputation_Rank                    str
 Employer_Reputation_Score               float64
 Employer_Reputation_Rank                    str
 Faculty_Student_Score                   float64
 Faculty_Student_Rank                        str
 Citations_per_Faculty_Score             float64
 Citations_per_Faculty_Rank                  str
 International_Faculty_Score             float64
 International_Faculty_Rank                  str
 International_Students_Score            float64
 International_Students_Rank                 str
 International_Research_Network_Score    float64
 International_Research_Network_Rank         str
 Employment_Outcomes_Score               float64
 Employment_Outcomes_Rank                    str
 Sustainability_Score                    float64
 Sustainability_Rank                         str
 Overall_Score                               str
 dtype: object)

In [44]:
file.isna()

,RANK_2025,RANK_2024,Institution_Name,Location,Region,SIZE,FOCUS,RES.,STATUS,Academic_Reputation_Score,...,International_Faculty_Rank,International_Students_Score,International_Students_Rank,International_Research_Network_Score,International_Research_Network_Rank,Employment_Outcomes_Score,Employment_Outcomes_Rank,Sustainability_Score,Sustainability_Rank,Overall_Score
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1500,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1501,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1502,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True

In [51]:
file['Sustainability_Rank']=pd.to_numeric(file['Sustainability_Rank'],errors='coerce')
file['Faculty_Student_Rank']=pd.to_numeric(file['Faculty_Student_Rank'],errors='coerce')
file['International_Faculty_Rank']=pd.to_numeric(file['International_Faculty_Rank'],errors='coerce')
file['Academic_Reputation_Rank']=pd.to_numeric(file['Academic_Reputation_Rank'],errors='coerce')
file['Employer_Reputation_Rank']=pd.to_numeric(file['Employer_Reputation_Rank'],errors='coerce')
file['Citations_per_Faculty_Rank']=pd.to_numeric(file['Citations_per_Faculty_Rank'],errors='coerce')
file['International_Students_Rank']=pd.to_numeric(file['International_Students_Rank'],errors='coerce')
file['International_Research_Network_Rank']=pd.to_numeric(file['International_Research_Network_Rank'],errors='coerce')
file['Employment_Outcomes_Rank']=pd.to_numeric(file['Employment_Outcomes_Rank'],errors='coerce')
file['Overall_Score']=pd.to_numeric(file['Overall_Score'],errors='coerce')

In [52]:
file.dtypes

RANK_2025                                   str
RANK_2024                                   str
Institution_Name                            str
Location                                    str
Region                                      str
SIZE                                        str
FOCUS                                       str
RES.                                        str
STATUS                                      str
Academic_Reputation_Score               float64
Academic_Reputation_Rank                float64
Employer_Reputation_Score               float64
Employer_Reputation_Rank                float64
Faculty_Student_Score                   float64
Faculty_Student_Rank                    float64
Citations_per_Faculty_Score             float64
Citations_per_Faculty_Rank              float64
International_Faculty_Score             float64
International_Faculty_Rank              float64
International_Students_Score            float64
International_Students_Rank             float64
International_Research_Network_Score    float64
International_Research_Network_Rank     float64
Employment_Outcomes_Score               float64
Employment_Outcomes_Rank                float64
Sustainability_Score                    float64
Sustainability_Rank                     float64
Overall_Score                           float64
dtype: object

In [53]:
file.isna()

,RANK_2025,RANK_2024,Institution_Name,Location,Region,SIZE,FOCUS,RES.,STATUS,Academic_Reputation_Score,...,International_Faculty_Rank,International_Students_Score,International_Students_Rank,International_Research_Network_Score,International_Research_Network_Rank,Employment_Outcomes_Score,Employment_Outcomes_Rank,Sustainability_Score,Sustainability_Rank,Overall_Score
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1498,False,False,False,False,False,False,False,False,False,False,...,True,False,True,False,True,False,True,False,True,True
1499,False,False,False,False,False,False,False,False,False,False,...,True,False,True,False,True,False,True,False,True,True
1500,False,False,False,False,False,False,False,False,False,False,...,True,False,True,False,True,False,True,False,True,True
1501,False,False,False,False,False,False,False,False,False,False,...,True,False,True,False,True,False,True,False,True,True
1502,False,False,False,False,False,False,False,False,True,False,...,True,False,True,False,True,False,True,False,True,True

In [54]:
file_drp=file.dropna()
file_drp

,RANK_2025,RANK_2024,Institution_Name,Location,Region,SIZE,FOCUS,RES.,STATUS,Academic_Reputation_Score,...,International_Faculty_Rank,International_Students_Score,International_Students_Rank,International_Research_Network_Score,International_Research_Network_Rank,Employment_Outcomes_Score,Employment_Outcomes_Rank,Sustainability_Score,Sustainability_Rank,Overall_Score
1,2,6,Imperial College London,United Kingdom,Europe,L,FC,VH,A,98.5,...,66.0,99.6,44.0,97.4,34.0,93.4,61.0,99.7,6.0,98.5
2,3,3,University of Oxford,United Kingdom,Europe,L,FC,VH,A,100.0,...,120.0,97.7,73.0,100.0,1.0,100.0,3.0,85.0,126.0,96.9
3,4,4,Harvard University,United States,Americas,L,FC,VH,B,100.0,...,269.0,69.0,215.0,99.6,5.0,100.0,1.0,84.4,130.0,96.8
6,7,7,ETH Zurich - Swiss Federal Institute of Techno...,Switzerland,Europe,L,FO,VH,A,98.8,...,25.0,98.6,63.0,95.7,64.0,90.5,73.0,98.8,18.0,93.9
9,10,15,California Institute of Technology (Caltech),United States,Americas,S,CO,VH,B,96.5,...,65.0,79.8,172.0,65.5,549.0,31.0,407.0,62.5,253.0,90.9
10,11,12,University of Pennsylvania,United States,Americas,L,FC,VH,B,96.3,...,188.0,66.2,226.0,91.9,137.0,100.0,7.0,93.0,71.0,90.3
11,12,10,"University of California, Berkeley (UCB)",United States,Americas,XL,FC,VH,A,100.0,...,182.0,61.0,242.0,97.2,39.0,98.4,23.0,100.0,2.0,90.1
23,24,24,Université PSL,France,Europe,L,CO,VH,A,74.4,...,315.0,65.0,230.0,99.8,3.0,97.1,33.0,73.4,197.0,84.7
24,25,21,University of Toronto,Canada,Americas,XL,FC,VH,A,99.7,...,132.0,96.1,90.0,97.7,29.0,98.7,19.0,100.0,1.0,84.1
27,28,37,Technical University of Munich,Germany,Europe,XL,FO,VH,A,83.0,...,236.0,98.6,64.0,95.6,68.0,34.5,365.0,93.1,70.0,83.2
28,29,30,McGill University,Canada,Americas,L,FC,VH,A,94.3,...,225.0,89.6,124.0,94.2,94.0,98.3,24.0,99.1,13.0,83.0
34,34,32,The University of Manchester,United Kingdom,Europe,XL,FC,VH,A,95.6,...,169.0,99.2,55.0,99.2,12.0,87.6,90.0,99.8,3.0,82.0
37,38,34,University of British Columbia,Canada,Americas,XL,FC,VH,A,98.3,...,142.0,72.8,200.0,96.2,53.0,74.6,141.0,99.8,4.0,81.0
38,39,50,Fudan University,China (Mainland),Asia,XL,FC,VH,A,85.7,...,201.0,35.1,390.0,67.2,519.0,64.4,183.0,82.7,142.0,80.3
40,40,43,The University of Queensland,Australia,Oceania,XL,FC,VH,A,86.7,...,54.0,100.0,23.0,96.7,47.0,56.7,214.0,96.7,36.0,80.2
44,45,51,Shanghai Jiao Tong University,China (Mainland),Asia,XL,FC,VH,A,84.0,...,558.0,19.6,553.0,73.7,424.0,73.5,144.0,80.3,154.0,77.8
48,49,47,Delft University of Technology,Netherlands,Europe,L,CO,VH,A,74.4,...,69.0,91.4,117.0,93.7,105.0,54.8,227.0,99.1,14.0,77.0
51,50,45,The London School of Economics and Political S...,United Kingdom,Europe,L,SP,VH,A,67.2,...,40.0,100.0,12.0,81.2,305.0,99.6,15.0,91.3,85.0,76.0
53,54,55,University of Bristol,United Kingdom,Europe,L,FC,VH,A,75.8,...,206.0,89.8,121.0,94.6,84.0,51.2,250.0,98.9,17.0,75.4
61,62,70,City University of Hong Kong,Hong Kong SAR,Asia,M,CO,VH,A,60.9,...,13.0,100.0,7.0,62.9,588.0,37.5,342.0,72.9,201.0,70.7
63,63,59,Sorbonne University,France,Europe,XL,FC,VH,A,87.2,...,471.0,46.7,315.0,99.8,4.0,79.7,125.0,87.6,111.0,70.3
68,69,67,The University of Warwick,United Kingdom,Europe,L,FC,VH,A,72.2,...,119.0,99.1,57.0,94.2,92.0,65.7,175.0,89.7,98.0,68.2
73,74,73,KTH Royal Institute of Technology,Sweden,Europe,L,FO,VH,A,45.2,...,175.0,65.9,227.0,91.1,155.0,62.4,191.0,94.8,58.0,65.7
74,75,85,Lund University,Sweden,Europe,L,FC,VH,A,68.3,...,124.0,73.4,198.0,96.7,48.0,86.5,95.0,99.6,8.0,65.6
77,78,76,University of Glasgow,United Kingdom,Europe,XL,FC,VH,A,77.4,...,141.0,99.4,49.0,97.6,30.0,33.5,378.0,98.5,20.0,65.0
78,79,73,Brown University,United States,Americas,M,FC,VH,B,59.9,...,239.0,50.9,289.0,83.2,277.0,63.6,186.0,46.6,333.0,64.7
79,80,84,University of Birmingham,United Kingdom,Europe,XL,FC,VH,A,68.9,...,171.0,89.3,127.0,97.5,31.0,44.5,285.0,96.8,35.0,64.1
80,80,81,University of Southampton,United Kingdom,Europe,L,FC,VH,A,50.1,...,173.0,98.0,70.0,97.1,40.0,49.2,261.0,96.9,34.0,64.1
88,89,78,Durham University,United Kingdom,Europe,L,FC,VH,A,59.6,...,125.0,84.9,153.0,89.7,172.0,39.4,326.0,98.6,19.0,61.7
95,96,111,University of Alberta,Canada,Americas,XL,FC,VH,A,57.0,...,116.0,71.0,207.0,96.0,55.0,70.0,159.0,97.6,28.0,61.2
107,108,100,University of Nottingham,United Kingdom,Europe,XL,FC,VH,A,61.1,...,194.0,70.5,208.0,98.0,25.0,38.0,339.0,97.0,33.0,58.5
108,109,121,Technical University of Denmark,Denmark,Europe,M,FO,VH,A,33.2,...,55.0,87.7,135.0,88.1,194.0,43.6,293.0,47.9,328.0,58.3
112,113,109,Aalto University,Finland,Europe,L,FO,VH,A,45.7,...,146.0,40.1,354.0,78.2,355.0,95.1,52.0,94.7,59.0,57.9
119,120,145,Queen Mary University of London,United Kingdom,Europe,L,FC,VH,A,48.3,...,96.0,99.2,54.0,92.5,127.0,21.4,534.0,95.6,54.0,55.8
121,122,173,Qatar University,Qatar,Asia,M,FC,VH,A,29.8,...,24.0,96.5,83.0,89.4,177.0,98.6,20.0,74.0,196.0,55.7
136,137,130,University of Vienna,Austria,Europe,XL,FC,VH,A,70.9,...,70.0,92.0,109.0,96.0,57.0,89.7,78.0,60.9,265.0,53.9
138,139,129,Chalmers University of Technology,Sweden,Europe,M,FO,VH,B,26.3,...,56.0,63.1,240.0,77.0,378.0,31.7,399.0,87.0,113.0,53.7
142,141,145,Rice University,United States,Americas,M,CO,VH,B,39.1,...,247.0,94.1,99.0,62.2,602.0,29.5,421.0,20.6,529.0,53.6
156,155,151,Wageningen University & Research,Netherlands,Europe,L,CO,VH,A,42.1,...,328.0,81.2,169.0,97.9,27.0,21.1,542.0,92.3,75.0,51.6
159,159,139,University of Groningen,Netherlands,Europe,XL,FC,VH,A,52.3,...,168.0,83.5,161.0,94.1,97.0,40.0,319.0,40.1,368.0,51.3
168,169,159,Ghent University,Belgium,Europe,XL,FC,VH,A,53.2,...,241.0,21.4,522.0,99.5,9.0,72.9,145.0,98.3,21.0,50.1
178,179,173,"The University of Newcastle, Australia (UON)",Australia,Oceania,L,FC,VH,A,28.3,...,89.0,24.2,487.0,82.0,289.0,14.8,670.0,92.4,74.0,48.7
183,184,167,University of York,United Kingdom,Europe,L,FC,VH,A,42.9,...,204.0,75.6,184.0,92.5,128.0,23.5,480.0,97.4,29.0,48.2
191,192,216,Tongji University,China (Mainland),Asia,XL,FC,VH,A,31.8,...,345.0,26.5,457.0,72.9,442.0,24.0,473.0,81.4,147.0,46.9
193,194,187,University of Gothenburg,Sweden,Europe,L,FC,VH,A,35.4,...,191.0,78.2,180.0,94.2,91.0,63.1,189.0,92.8,73.0,46.7
214,215,228,National Cheng Kung University (NCKU),Taiwan,Asia,L,FC,VH,A,51.5,...,646.0,13.9,642.0,58.7,648.0,42.4,306.0,83.8,131.0,44.2
227,227,239,Rheinische Friedrich-Wilhelms-Universität Bonn,Germany,Europe,L,FC,VH,A,52.8,...,399.0,38.9,361.0,94.7,83.0,35.4,357.0,83.2,138.0,43.5
232,233,210,University of Twente,Netherlands,Europe,M,CO,VH,A,20.7,...,83.0,90.4,119.0,87.6,202.0,20.0,562.0,13.8,603.0,42.7
272,273,292,University College Cork,Ireland,Europe,L,FC,VH,A,30.1,...,198.0,52.1,281.0,69.1,497.0,34.0,371.0,91.0,88.0,38.3
273,273,289,University of Galway,Ireland,Europe,L,FC,VH,A,26.2,...,144.0,43.2,333.0,81.3,301.0,46.6,274.0,85.9,120.0,38.3
305,306,336,Aalborg University,Denmark,Europe,L,FC,VH,A,19.9,...,250.0,14.9,627.0,92.1,134.0,23.3,486.0,75.6,183.0,35.7
312,312,306,University of Johannesburg,South Africa,Africa,L,CO,VH,A,17.7,...,134.0,51.4,285.0,98.0,26.0,63.1,190.0,65.6,238.0,35.0
317,316,304,University of Notre Dame,United States,Americas,L,CO,VH,B,25.8,...,566.0,18.4,575.0,70.1,484.0,60.2,201.0,68.9,225.0,34.7

In [65]:
file['Score_Category']=np.where(file['Overall_Score']>=90,'Elite',
                            np.where(file['Overall_Score']>=75,'High',
                                np.where(file['Overall_Score']>=50,'Medium',
                                    'Low',)))

In [68]:
file[['Score_Category','Overall_Score']]

     Score_Category  Overall_Score
0             Elite          100.0
1             Elite           98.5
2             Elite           96.9
3             Elite           96.8
4             Elite           96.7
...             ...            ...
1498            Low            NaN
1499            Low            NaN
1500            Low            NaN
1501            Low            NaN
1502            Low            NaN

[1503 rows x 2 columns]