pivot and melt  - used to reshape the file

In [2]:
 import numpy as np 
 import pandas as pd

In [3]:
data=pd.read_csv("sample_sales_dataset_25_rows.csv")

In [4]:
data

          Date Product Region  Sales  Units    Rep    Month Quarter
0   2023-01-01       C   West    564     59    Bob  January      Q1
1   2023-01-02       A   East    959     45  Alice  January      Q1
2   2023-01-03       A   East    871     89  David  January      Q1
3   2023-01-04       B   East    590      9   John  January      Q1
4   2023-01-05       D  North    811     23    Bob  January      Q1
5   2023-01-06       C   East    151     44   John  January      Q1
6   2023-01-07       D   West    829     32   John  January      Q1
7   2023-01-08       D  North    494     56  Alice  January      Q1
8   2023-01-09       C   East    785     51    Bob  January      Q1
9   2023-01-10       C  South    758     28    Bob  January      Q1
10  2023-01-11       A  North    502     97    Bob  January      Q1
11  2023-01-12       D   West    857     85   John  January      Q1
12  2023-01-13       D   West    906     76   John  January      Q1
13  2023-01-14       C  North    891     89    Bob  January      Q1
14  2023-01-15       C  South    927     98  David  January      Q1
15  2023-01-16       D  South    382     80    Bob  January      Q1
16  2023-01-17       D   East    805     80   John  January      Q1
17  2023-01-18       B  South    471     30    Bob  January      Q1
18  2023-01-19       D  South    303     31   Mary  January      Q1
19  2023-01-20       B  South    503     34  David  January      Q1
20  2023-01-21       B   East    177     89  David  January      Q1
21  2023-01-22       D   East    588    100  Alice  January      Q1
22  2023-01-23       C  North    592     94  Alice  January      Q1
23  2023-01-24       D   West    455     39  David  January      Q1
24  2023-01-25       B  North    593     52   John  January      Q1

In [7]:
pd.pivot_table(data,values='Sales',index='Region',columns='Product',aggfunc='median')

Product      A      B      C      D
Region
East     915.0  383.5  468.0  696.5
North    502.0  593.0  741.5  652.5
South      NaN  487.0  842.5  342.5
West       NaN    NaN  564.0  843.0

In [8]:
pivot2=pd.pivot_table(data,values=['Sales','Units'],index='Region',columns='Product')

In [9]:
pivot2

         Sales                       Units
Product      A      B      C       D     A     B     C     D
Region
East     915.0  383.5  468.0  696.50  67.0  49.0  47.5  90.0
North    502.0  593.0  741.5  652.50  97.0  52.0  91.5  39.5
South      NaN  487.0  842.5  342.50   NaN  32.0  63.0  55.5
West       NaN    NaN  564.0  761.75   NaN   NaN  59.0  58.0

crosstabs-used counting function

In [10]:
pd.crosstab(data['Region'],data['Product'])

Product  A  B  C  D
Region
East     2  2  2  2
North    1  1  2  2
South    0  2  2  2
West     0  0  1  4